/*!
Contains the Structural trait
*/

/// Marker trait for types that implement some field accessor traits.
///
/// By default the `Structural` derive macro
/// puts documentation on the Structural trait implementation
/// describing the accessor trait impls generated by it.
pub trait Structural {}
